update to 10.0.1
KhiopsML/khiops pull request #10
Opened 2023-06-21 14:11 UTC by bruno-at-orange

Update all source files to **Khiops v10.0.1**

2023-06-21 14:48 UTC, felipe-olmos-orange requested changes
After addressing the comments LGTM

2023-06-21 14:48 UTC, felipe-olmos-orange commented on src/Learning/MODL/MODL.rc
This one is again in UTF16. I think we should revert it to the previous version.

2023-06-21 14:48 UTC, felipe-olmos-orange commented on src/Parallel/PLParallelTask/resourceManager.log.ref
I think this should be not included

2023-06-22 07:37 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/resourceManager.log.ref
I will move it in test/Parallel/results.ref/

2023-06-22 08:31 UTC, felipe-olmos-orange commented on src/Learning/MODL/MODL.rc
So in the end you just eliminated it?

2023-06-22 08:52 UTC, felipe-olmos-orange commented on src/Learning/MODL/MODL.rc
Ok, it was left to the last version.

2023-06-22 08:53 UTC, felipe-olmos-orange approved these changes

2023-06-22 09:14 UTC, merged