203 switch to openmpi for linux packages
KhiopsML/khiops pull request #229
Opened 2024-04-09 12:43 UTC by bruno-at-orange

2024-04-16 12:58 UTC, folmos-at-orange requested changes
Mostly cosmetic stuff.

One question: It is possible to have just one binary which can be linked to both OpenMPI and MPICH ?

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/actions/build-khiops/action.yml
> +      if: ${{ runner.os == 'Windows' }}
`${{ }}` is not necessary in `if` statements. You may write
```yaml
if: runner.os == 'Windows'
```

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/actions/build-khiops/action.yml
> +      if: ${{ runner.os == 'macOS' }}
`${{ }}` is not necessary in `if` statements.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/actions/build-khiops/action.yml
> +      if: ${{ runner.os == 'Linux' }}
`${{ }}` is not necessary in `if` statements.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-debian.yml
> +        #continue-on-error: ${{ matrix.os == 'debian:11' }}
If this isn't a problem anymore then it should be removed.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-debian.yml
> +        #continue-on-error: ${{ matrix.os == 'debian:11' }}
If this isn't a problem anymore then it should be removed.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-rpm.yml
> +          module load mpi/${{ env.MPI_IMPLEMENTATION}}-x86_64
If it is in the environment I'd use `$MPI_IMPLEMENTATION`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-rpm.yml
> +            echo "MPI_IMPLEMENTATION=${{ github.event.inputs.mpi_implementation }}" >> "$GITHUB_ENV"
A simpler way to do this is
```bash
MPI_IMPLEMENTATION="${{ inputs.mpi_implementation || 'openmpi' }}"
echo "MPI_IMPLEMENTATION=$MPI_IMPLEMENTATION" >> "$GITHUB_ENV"
```
or even

```bash
echo "MPI_IMPLEMENTATION=${{ inputs.mpi_implementation || 'openmpi' }}" >> "$GITHUB_ENV"
```

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-rpm.yml
> +          fi
I'd use any of the simplifications mentioned above.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os == 'Windows' }}
`if` statements don't require `${{ }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-debian.yml
> +          update-alternatives --set mpirun /usr/bin/mpirun.${{ env.MPI_IMPLEMENTATION }}
If it is in env you may use just `$MPI_IMPLEMENTATION`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/pack-debian.yml
> +
You may use one of the simplifications mentioned below.

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os == 'Windows' }}
`if` statements dont require `${{ ... }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os != 'Windows' }}
`if` statements don't require `${{ }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os == 'Windows' }}
`if` statements don't require `${{ }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os == 'macOS' }}
`if` statements don't require `${{ }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +        if: ${{ runner.os == 'Linux' }}
`if` statements don't require `${{ }}`

2024-04-16 12:58 UTC, folmos-at-orange commented on .github/workflows/run-standard-tests.yml
> +          if [ "${{ github.event.inputs.warning_as_error }}" == "true" ] && grep -q "warning" results/errors.txt  ; then
You may use `inputs.warnings_as_error` instead of `github.event.inputs.warnings_as_error`

2024-04-16 12:58 UTC, folmos-at-orange commented on test/LearningTestTool/py/_kht_utils.py
> +    return False
Maybe simpler with
```python
return (tool_exe_name in kht.TOOL_EXE_NAMES.values() or extract_tool_exe_name(tool_exe_name) in kht.PARALLEL_TOOL_NAMES)
```

2024-04-16 13:34 UTC, bruno-at-orange commented on .github/actions/build-khiops/action.yml
> +      if: ${{ runner.os == 'Windows' }}
done

2024-04-16 13:48 UTC, bruno-at-orange commented on .github/workflows/pack-rpm.yml
> +            echo "MPI_IMPLEMENTATION=${{ github.event.inputs.mpi_implementation }}" >> "$GITHUB_ENV"
OK, nice...

2024-04-26 08:05 UTC, folmos-at-orange commented
I added two commits.

Good news:
The Linux packages pass the LearningTest battery.

Bad news:
The conda packages are very difficult make work with openmpi so I left them with MPICH. More details in the internal email.

2024-04-26 13:33 UTC, folmos-at-orange approved these changes
I think the version should be changed. See comment.

If it is possible, could we have a "no suffix" generation even if MPI is available ? In conda we do not need the suffixes, and it simplifies the lookup for the executable. At the moment I just rename it after the build.

2024-04-26 13:33 UTC, folmos-at-orange commented on src/Learning/KWUtils/KWKhiopsVersion.h
> +#define KHIOPS_VERSION KHIOPS_STR(10.2.2-b0)
To be SemVer compatible the version should be `10.2.2-b.0` (a period `.` between the `b` and the `0`)

2024-05-06 16:09 UTC, merged