3 use targets in cmake to speed up the build process
KhiopsML/khiops pull request #26
Opened 2023-06-28 11:39 UTC by bruno-at-orange

- Use target in cmake build
- Remove several options in the main CMakeLists:
    - FULL, LEARNING and PARALLEL: not needed anymore (use targets)
    - MODL_SO: binary MODL_dll is always built
    - FEDORA: the fedora distro is discovered automatically and a fatal error is triggered if MPI_SUFFIX is not set by the mpi module
- Change the name of some test targets: all in lowercase
- CMakePresets:
    - add `"jobs":0` to enable parallel build
    -  simplification of the naming: remove the prefix "build_" in the name of the build preset

2023-06-28 12:56 UTC, felipe-olmos-orange requested changes

2023-06-28 12:56 UTC, felipe-olmos-orange commented on .github/workflows/pack-debian.yml
> +      run: time cmake --build ${{github.workspace}}/build --parallel --target MODL MODL_Coclustering KhiopsNativeInterface
No need to use `time`. Github itselft times it

2023-06-28 12:56 UTC, folmos-at-orange commented on .github/workflows/pack-rpm.yml
> +      run: cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering KhiopsNativeInterface
I think you are building two times. The configure step does not use a preset nor uses `-C`

2023-06-28 12:56 UTC, folmos-at-orange commented on .github/workflows/run-unit-tests.yml
> +        run: mpiexec  -n 4 build/${{ matrix.build-setup.cmake-preset }}/bin/parallel_mpi_test --gtest_output="xml:${{github.workspace}}/reports/report-parallel-mpi.xml"
Nitpick: Remove extra space here.

2023-06-28 12:56 UTC, folmos-at-orange commented on CMakeLists.txt
> +# Build Norm Parallel and Learning modules
"Build" is confusing as it we are only defining targets. Maybe "Add targets for Norm Parallel and Learning modules" ?

2023-06-28 12:56 UTC, folmos-at-orange commented on README.md
> +On Fedorra-like distro, the environment module mpi must be loaded before configure, build and package processes:
Fedo**rr**a -> Fedora

2023-06-28 12:56 UTC, folmos-at-orange commented on packaging/install.cmake
> +endif(NOT IS_FEDORA_LIKE)
We should discus whether use this CMake feature of "commenting" the `endif`. I find it confusing, mostly when there are `else` and or `elseif` expressions.

2023-06-28 12:56 UTC, folmos-at-orange commented on .github/workflows/pack-rpm.yml
> +      run: cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering KhiopsNativeInterface
Also in the configure step shouldn't `CMAKE_BUILD_TYPE=Release` . I would put it even if it is the default value.

2023-06-28 12:56 UTC, felipe-olmos-orange commented
Another point: The macos parallel unit-test are failing because of java (???)

2023-06-28 14:01 UTC, bruno-at-orange commented on .github/workflows/pack-rpm.yml
> +      run: cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering KhiopsNativeInterface
nope `cmake -B build` configure and `cmake --build build` build....
However `CMAKE_BUILD_TYPE=Release` is missing, I think the default value is 'Debug`

2023-06-28 14:24 UTC, bruno-at-orange commented
For the macos unit-test, I don't think it is because of java: java is not used !

2023-06-28 14:38 UTC, felipe-olmos-orange commented
> For the macos unit-test, I don't think it is because of java: java is not used !

The failed test says `fatal error : Java GUI : Java GUI is not available on MacOS`

See: https://github.com/KhiopsML/khiops/actions/runs/5402237529/jobs/9813233296?pr=26#step:6:55

2023-06-28 14:50 UTC, bruno-at-orange commented
> > For the macos unit-test, I don't think it is because of java: java is not used !
> 
> The failed test says `fatal error : Java GUI : Java GUI is not available on MacOS`
> 
> See: https://github.com/KhiopsML/khiops/actions/runs/5402237529/jobs/9813233296?pr=26#step:6:55

It is weird because on runners (windows and linux), GUI is not available and tests passed. There is an issue in macOS porting.

2023-06-28 15:08 UTC, felipe-olmos-orange commented on .github/workflows/pack-rpm.yml
> +      run: cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering KhiopsNativeInterface
Ok !

2023-06-28 15:36 UTC, folmos-at-orange commented
> > > For the macos unit-test, I don't think it is because of java: java is not used !
> > 
> > 
> > The failed test says `fatal error : Java GUI : Java GUI is not available on MacOS`
> > See: https://github.com/KhiopsML/khiops/actions/runs/5402237529/jobs/9813233296?pr=26#step:6:55
> 
> It is weird because on runners (windows and linux), GUI is not available and tests passed. There is an issue in macOS porting.

It is really weird. Since it works in serial maybe it is a slave process that tries to instantiate an UIObject or something like that. I will make an issue of it.

2023-06-28 15:38 UTC, felipe-olmos-orange commented
Last issue: RPM packaging is broken because of the missing pdfs. Maybe we should fix that before merging ? Since you changed the build process it would be good to verify that the packaging processes work as well.

2023-06-28 16:25 UTC, bruno-at-orange commented
> Last issue: RPM packaging is broken because of the missing pdfs. Maybe we should fix that before merging ? Since you changed the build process it would be good to verify that the packaging processes work as well.

OK I will do it

2023-06-29 11:53 UTC, felipe-olmos-orange approved these changes

2023-06-29 12:11 UTC, merged