317 the test testkhiopstextvariablestextloadfile provokes segmentation fault in macos
KhiopsML/khiops pull request #329
Opened 2024-07-02 16:46 UTC by bruno-at-orange

The only commit to consider is c7d2666aa3fdd53e823df314ebe9a8ff994cd754
The other commits will be deleted before the merge, they consists in adding the TextLoadFile test in the CI

2024-07-03 08:17 UTC, marcboulle requested changes
Je pense que la correction corrige le bug.

Une question: pourquoi le problème se pose sur macOS et pas sur linux?

On peut en profiter pour clarifier le comportement de certaines fonctions IO de bas niveau

#### Comportement actuel des IO bas niveaux

SystemFile:
- // Renvoie le nombre d'octets lus, 0 si erreur ou fin de fichier
  longint Read(void* pBuffer, size_t size, size_t count);
- // Renvoie le nombre d'octets ecrits, 0 si il y a eu une erreur
  longint Write(const void* pBuffer, size_t size, size_t count);

SystemFileDriver:
- // Renvoie le nombre d'octets lus, -1 si il y a eu une erreur
  virtual longint Fread(void* ptr, size_t size, size_t count, void* stream) = 0;
- // Renvoie le nombre d'octets ecrits, 0 si il y a eu une erreur
  virtual longint Fwrite(const void* ptr, size_t size, size_t count, void* stream) = 0;

SystemFileDriverLibrary: idem

Remarque:
- le comportement de Fread est différent de celui du C ansi, qui ne renvoie pas -1 et impose de passer par ferror
  - fread: https://en.cppreference.com/w/c/io/fread
  - fwrite: https://en.cppreference.com/w/c/io/fwrite
- pourvu que ce soit bien clair: pas de problème
  - ou faut-il ajouter une fonction SystemFile::Error() et SystemFileDriver::Ferror()?
  - plus Feof()

#### Problèmes potentiels

~~~
longint SystemFileDriverANSI::Fread(void* ptr, size_t size, size_t count, void* stream)
{
	longint lRes;

	// Lecture dans le fichier
	lRes = std::fread(ptr, size, count, (FILE*)stream);
	if (lRes != longint(count) and ferror((FILE*)stream))
		lRes = -1;
	return lRes;
}
~~~
Problème:
- l'implementation n'est pas conforme à la spécification
- remplacer par?
~~~
	if (ferror((FILE*)stream))
		lRes = -1;
~~~
- SystemFileDriverANSI::Fwrite: idem

2024-07-30 12:59 UTC, bruno-at-orange commented
La segmentation fault se produit également sur Linux (test sur branche dev).
J'ai corrigé `SystemFileDriverANSI::Fread `et `SystemFileDriverANSI::Fwrite`. ça corrige le bug avec un impact minimal.
Il reste à décider si on ajoute `SystemFile::Error() `et `SystemFileDriver::Ferror() `? Peut-être qu'on peut faire ça en prenant en compte la nouvelel API des drivers?

2024-10-07 08:34 UTC, bruno-at-orange commented
Je propose de limiter le scope de cette PR à la correction du bug.
Je créerai ensuite une issue concernant la modification de l'API des drivers.

2024-10-18 09:07 UTC, marcboulle requested changes
LGTM

Remarque mineure: passer toutes les méthodes en inline de SystemFile.h vers SystemFile.cpp (pas de raison d'être en inline)

Sinon: nettoyer les test temporaires et faire un seul point de commit

2024-10-18 09:30 UTC, marcboulle approved these changes
LGTM

2024-10-18 09:33 UTC, merged