Finalize implementation of Khiops interpretation
KhiopsML/khiops pull request #359
Opened 2024-08-23 09:51 UTC by n-voisine

Corrections des noms et info-bulle
Prise en compte de message de warning pour la regression et l'utilisation de group target values Prise en compte du code de fin 2023

2025-01-06 09:26 UTC, marcboulle requested changes
Quelques correction mineures

Une passe de nettoyage du code sera à prévoir par la suite

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  	cImportanceValueCorrected = 1 / log(2.0) * log(cRatioCorrected);
Réécrire en `cImportanceValueCorrected = log(cRatioCorrected)/ log(2.0);` ?

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  	    1 / log(2.0) * (log(cInitialScoreCorrected) - log(cScoreWithoutOneVariableCorrected));
Ré-écrire en `cImportanceValueCorrected =(log(cInitialScoreCorrected) - log(cScoreWithoutOneVariableCorrected))/ log(2.0);`

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  							if (cScore > cMaxScore)
Il me semble qu'il y a un risque d'instabilité numérique, quand un score va dépasser une autre a epsilon près.

Suggestion: utiliser `if (KWContinuous::CompareIndicatorValue(cScore, cMaxScore) > 0)` au lieu de `if (cScore > cMaxScore)`, avec un commentaire préalable.

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +		// supprimer les eventuels attributs d'interpretation qui preexisteraient dans le dico, afin de gerer correctement les mises a jour des parametres via IHM (on recree systematiquement tous les attri
Commentaire trop long: a mettre sur deux lignes

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +	//NV
Pourquoi tout ce qui suit est commenté par NV???

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +	attribute->GetMetaData()->SetNoValueAt("ReinforcementVariable"); //, soNativeAttributeName->GetString());
Une partie des MetaData est paramétrée via des constantes (ex: INTERPRETATION_ATTRIBUTE_META_TAG).
Une autre par des valeurs en dur (ex: "ReinforcementVariable")
A corriger plus tard, dans le nettoyage du code

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +	//if (interpretationSpec->GetHowAttributesNumber() == oaNativePredictiveAttributeNames.GetSize() and
Je ne comprend pas pourquoi ces tests sont commentés, ou non.

De façon générales, tout ce code commenté rend la relecture plus que complexe.
Le nettoyage du code va vite devenir important.

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.h
>  	const Symbol SHAPLEY_LABEL = "Shapley";
Utiliser des ALString, et non des Symbol, pour déclarer des constantes de type chaines de caractères

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIPredictorInterpretationView.cpp
> +	    ->SetHelpText("Build an interpretation dictionary that computes the variable importances and reinforcement "
"variable importances" -> "importance of variables"

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +	AddIntField("WhyNumber", "Number of variables importances written", 0);
"Number of variables importances written" -> "Number of written variable importances"

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +	    ->SetHelpText("Number of variables importances written in the output file. By default, all the variables "
"Number of variables importances written" ->"Number of variable importances written"

2025-01-06 09:26 UTC, marcboulle commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +			  "predictor variable. By default, all target variables are taken into account.");
"all target variables" -> "all target vlues"

2025-01-06 10:04 UTC, marcboulle requested changes

2025-01-06 10:04 UTC, marcboulle commented on src/Learning/KIInterpretation/KIHowParameterView.cpp
> +	GetFieldAt("leverVariablesSpecView")
Supprimer l'aide sur "leverVariablesSpecView", qui est une boite de dialogue et non un champ terminal

2025-01-06 10:04 UTC, marcboulle commented on src/Learning/KIInterpretation/KIPredictorInterpretationView.cpp
>  			// initialiser la liste des variables leviers en fonction du dictionnaire d'interpretation que
"No dictionary has been loaded for interpretation" -> "No available classifier dictionary for interpretation"

"The chosen dictionary is not a classifier that can be handled for interpretation" -> "The selected analysis dictionary " + sClassName  + " is not a classifier that can be used for interpretation"

Et remplacer `sClassName = "";`par `SetStringValueAt("ClassName", sClassName);`
(sinon, on ne comprend pas de quel dictionnaire on parle)

2025-01-06 10:04 UTC, marcboulle commented on src/Learning/KIInterpretation/KIHowParameterView.cpp
> +	GetFieldAt("HowClass")->SetHelpText("Class value for which one try to increase the probability of occurrence.");
"Class value for which one try to increase the probability of occurrence."

On ne comprend pas le cas "No value" qui est en première valeur
- remplacer par "" (sinon, rsique de conflit avec un variable cible ayant une valeur "No value")
- expliquer dans l'aide à quoi cela correspond

2025-01-06 10:14 UTC, marcboulle requested changes

2025-01-06 10:14 UTC, marcboulle commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +			Global::AddWarning("Interpret model", "", "Group Target not yet implemented");
"Group Target not yet implemented" -> "Interpretation dictionary not yet implemented for classifier with grouped target values"

Il ne pourrait pas y avoir un message similaire pour les régresseurs?

2025-01-06 13:08 UTC, n-voisine commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  	cImportanceValueCorrected = 1 / log(2.0) * log(cRatioCorrected);
FAIT

2025-01-06 13:09 UTC, n-voisine commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  	    1 / log(2.0) * (log(cInitialScoreCorrected) - log(cScoreWithoutOneVariableCorrected));
FAIT

2025-01-06 13:11 UTC, n-voisine commented on src/Learning/KIInterpretation/KIDRPredictor.cpp
>  							if (cScore > cMaxScore)
FAIT

2025-01-06 13:12 UTC, n-voisine commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +		// supprimer les eventuels attributs d'interpretation qui preexisteraient dans le dico, afin de gerer correctement les mises a jour des parametres via IHM (on recree systematiquement tous les attri
FAIT

2025-01-06 13:17 UTC, n-voisine commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +	//NV
Ce sont les attributs du classiffieur ils était généré avant modification mais la je  garde le code au cas ou contre ordre .. à nettoyer

2025-01-06 13:40 UTC, n-voisine commented on src/Learning/KIInterpretation/KIInterpretationDictionary.h
>  	const Symbol SHAPLEY_LABEL = "Shapley";
FAIT

2025-01-06 13:43 UTC, n-voisine commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +	AddIntField("WhyNumber", "Number of variables importances written", 0);
FAIT

2025-01-06 13:44 UTC, n-voisine commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +	    ->SetHelpText("Number of variables importances written in the output file. By default, all the variables "
FAIT

2025-01-06 13:45 UTC, n-voisine commented on src/Learning/KIInterpretation/KIWhyParameterView.cpp
> +			  "predictor variable. By default, all target variables are taken into account.");
FAIT

2025-01-06 13:49 UTC, n-voisine commented on src/Learning/KIInterpretation/KIHowParameterView.cpp
> +	GetFieldAt("leverVariablesSpecView")
FAIT

2025-01-06 13:54 UTC, n-voisine commented on src/Learning/KIInterpretation/KIPredictorInterpretationView.cpp
>  			// initialiser la liste des variables leviers en fonction du dictionnaire d'interpretation que
FAIT

2025-01-06 13:58 UTC, n-voisine commented on src/Learning/KIInterpretation/KIHowParameterView.cpp
> +	GetFieldAt("HowClass")->SetHelpText("Class value for which one try to increase the probability of occurrence.");
FAIT

2025-01-06 13:59 UTC, n-voisine commented on src/Learning/KIInterpretation/KIInterpretationDictionary.cpp
> +			Global::AddWarning("Interpret model", "", "Group Target not yet implemented");
FAIT

2025-01-06 16:48 UTC, n-voisine commented on src/Learning/KIInterpretation/KIPredictorInterpretationView.cpp
> +	    ->SetHelpText("Build an interpretation dictionary that computes the variable importances and reinforcement "
FAIT

2025-01-07 09:38 UTC, marcboulle approved these changes
OK pour une beta

Mais il est vraiment indispensable de nettoyer le code et le le rendre conforme aux normes de développement et de nommage. Cf. issue https://github.com/KhiopsML/khiops/issues/453

2025-01-07 10:41 UTC, merged