338 improve memory dimensioning for snb training
KhiopsML/khiops pull request #362
Opened 2024-08-30 12:08 UTC by folmos-at-orange

2024-08-30 15:30 UTC, marcboulle requested changes

2024-08-30 15:30 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMTaskResourceRequirement.h
typo (trois fois):
- "on reparti" -> "on repartit"

2024-08-30 15:30 UTC, marcboulle commented on src/Learning/SNBPredictor/SNBPredictorSelectiveNaiveBayesTrainingTask.cpp
Je ne comprend pas clairement al logique du code conditionné par (nSliceNumber = 2)

J'aurais plutôt mis le code en fin de boucle, en cas d'échec pour une slice?
~~~
	// Finalisation si la memoire attribue est assez pour ce nombre de slices
	if (lSlaveGrantedMemory >= lSlaveNecessaryMemory)
           ...  

	// En cas d'echec, memorisation de la quantite extra de memoire pour pouvoir s'executer avec une seule slice
	else (nSliceNumber == 2)
		lOneSliceExecutionExtraNecessaryMemory = lSlaveNecessaryMemory - lSlaveGrantedMemory 
~~~

2024-08-30 15:38 UTC, folmos-at-orange commented on src/Learning/SNBPredictor/SNBPredictorSelectiveNaiveBayesTrainingTask.cpp
Ok, I'll refactor that way.

2024-08-30 15:41 UTC, folmos-at-orange commented on src/Parallel/PLParallelTask/RMTaskResourceRequirement.h
Ok & Done.

2024-08-30 15:48 UTC, marcboulle commented
Un premier résultat étonnant sur LearningTest\TestKhiops\MTClassification\MTConnect4Extended:
C'est pire qu'avant: on passe de "(needs extra 2.5 GB)" à (needs extra 8.1 GB)

2024-08-30 15:49 UTC, folmos-at-orange commented on src/Learning/SNBPredictor/SNBPredictorSelectiveNaiveBayesTrainingTask.cpp
Done

2024-09-02 14:32 UTC, folmos-at-orange commented
> Sur certains jeux de données, il n'y a plus besoin de slices.
> 
> Par contre, sur d'autres, c'est pire qu'avant:
> 
> * LearningTest\TestKhiops\MTClassification\MTConnect4Extended:
>   Number of slices: 2 (needs extra 2.5 GB) => Number of slices: 2 (needs extra 8.1 GB)
> * LearningTest\TestKhiops\SmallInstability\AIDS10000
>   Number of slices: 4 (needs extra 1.3 GB) => Number of slices: 2 (needs extra 1.9 GB)

It was only a bug in the reporting of the remaining memory.

2024-09-04 09:11 UTC, marcboulle approved these changes
Tout est ok sur LearningTest (complete)
Perfect

2024-09-04 09:29 UTC, merged