Fix slice memory estimation
KhiopsML/khiops pull request #369
Opened 2024-09-06 11:53 UTC by folmos-at-orange

2024-09-06 12:20 UTC, marcboulle requested changes
La méthode ComputeGlobalSlaveNecessaryMemory, dont le deuxième paramètre a changé radicalement de valeur, est utilisée plusieurs fois dans le code, avec une variation de paramètre (MemSegmentByteSize, BufferedFile::nDefaultBufferSize).

Et réciproquement, elle utilise pour son implémentation d'autres méthodes internes (ComputeRecodingObjectsNecessaryMemory, ComputeSliceSetTotalReadBufferNecessaryMemory, ComputeSliceSetTotalReadBufferNecessaryMemory).

Il faudrait vérifier si le changement proposé ne doit pas être propagé à d'autres méthodes.

2024-09-06 12:20 UTC, marcboulle commented on src/Learning/SNBPredictor/SNBPredictorSelectiveNaiveBayesTrainingTask.cpp
> +		//     lors de la estimation de resources. Ceci assure que on est au dessus de la borne-inf.
typo: "de la estimation" -> "de l'estimation"

2024-09-06 14:02 UTC, folmos-at-orange commented
> La méthode ComputeGlobalSlaveNecessaryMemory, dont le deuxième paramètre a changé radicalement de valeur, est utilisée plusieurs fois dans le code, avec une variation de paramètre (MemSegmentByteSize, BufferedFile::nDefaultBufferSize).
> 
> Et réciproquement, elle utilise pour son implémentation d'autres méthodes internes (ComputeRecodingObjectsNecessaryMemory, ComputeSliceSetTotalReadBufferNecessaryMemory, ComputeSliceSetTotalReadBufferNecessaryMemory).
> 
> Il faudrait vérifier si le changement proposé ne doit pas être propagé à d'autres méthodes.

The function it is used in two places:
- Twice in `ComputeResourceRequirements` to estimate the min and the max global memory
- Once in `MasterInitializeDataTableBinarySliceSet` to compute the number of slices after the resources have been assigned.

In `MasterInitializeDataTableBinarySliceSet` it was called with `MemSegmentByteSize` but this **increases** the necessary memory (see the comment in the code) with respect to `BufferedFile::nDefaultBufferSize`. So it must be called with the `BufferedFile:nDefaultBufferSize` so we reach the lower bound (`SetMin`) of the requested memory.

2024-09-06 17:44 UTC, folmos-at-orange commented
I ran LearningTest:
- All Ok (with the usual exceptions)
- No database was sliced for the SNB

2024-09-09 13:15 UTC, folmos-at-orange commented
Added after offline discussion: Silence the removal of temporary dictionary files

2024-09-10 09:12 UTC, folmos-at-orange commented on src/Learning/SNBPredictor/SNBPredictorSelectiveNaiveBayesTrainingTask.cpp
> +		//     lors de la estimation de resources. Ceci assure que on est au dessus de la borne-inf.
Ok & Done.

2024-09-17 07:12 UTC, marcboulle approved these changes

2024-09-17 08:12 UTC, merged