384 use all processes in the gui
KhiopsML/khiops pull request #387
Opened 2024-10-01 08:33 UTC by bruno-at-orange

Fix "Max number of processor cores" in the GUI

- In the Khiops GUI, the "Max number of processor cores" is now bounded by the number of physical cores (not minus one).
2 now useless methods are removed from `KWSystemParametersView`:
    - ComputeCoreNumber
    - ComputeRequestedCoreNumber
- 2 methods used RMResourceConstraints::GetMaxCoreNumberOnCluster() wrongly. It returns the number of cores on the system without regard to the user constraints and resource requirements.

2024-10-02 07:01 UTC, n-voisine approved these changes
LGTM

2024-10-07 09:10 UTC, marcboulle requested changes
LGTM
Petites améliorations de détail dans KWDatabaseIndexer

2024-10-07 09:10 UTC, marcboulle commented on src/Learning/KWDataUtils/KWDatabaseIndexer.cpp
> +	RMTaskResourceRequirement requirements;
renommer:
- requirements en defaultRequirements
- grantedResources en defaultGrantedResources

2024-10-07 09:10 UTC, marcboulle commented on src/Learning/KWDataUtils/KWDatabaseIndexer.cpp
>  	// Memorisation du nombre d'esclaves utilisables au moment de l'indexation
Changer le commentaire en 
// Memorisation du nombre d'esclaves utilisables au moment de l'indexation
// Pour cela, les ressources obtenues pour des exigences par defaut fournissent le nombre total d'esclaves disponibles

2024-10-09 07:50 UTC, bruno-at-orange commented on src/Learning/KWDataUtils/KWDatabaseIndexer.cpp
> +	RMTaskResourceRequirement requirements;
done

2024-10-09 07:51 UTC, bruno-at-orange commented on src/Learning/KWDataUtils/KWDatabaseIndexer.cpp
>  	// Memorisation du nombre d'esclaves utilisables au moment de l'indexation
done

2024-10-09 11:27 UTC, marcboulle approved these changes
LGTM

2024-10-09 11:28 UTC, merged