378 rmparallelresourcemanager unit test fails on macos and windows
KhiopsML/khiops pull request #411
Opened 2024-10-16 13:32 UTC by bruno-at-orange

- Improve `PLHostClassSolution` sort: we now take into account the master HostClass
  the resource allocation is now reproducible
- Run test using GUI only if GUI is available: we don't want to raise an error that varies with the os

2024-10-16 14:39 UTC, marcboulle requested changes

2024-10-16 14:39 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	// le test suivant est lance uniquemlent si on est en mode graphique, ce qui n'est pas le cas
uniquement

2024-10-16 14:39 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	int nCompare = 0;
ajouter un require(solution1->GetHostClass()->IsMasterClass() != solution2->GetHostClass()->IsMasterClass())

2024-10-16 14:39 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +		nCompare = CompareLongint(solution1->GetHostClass()->GetDefinition()->GetMemoryMin(),
en cas d'égalité, ajouter une comparaison sur la ressource suivante (disk) (ou les ressources suivantes)

2024-10-16 15:58 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	// le test suivant est lance uniquemlent si on est en mode graphique, ce qui n'est pas le cas
ok

2024-10-16 16:00 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	int nCompare = 0;
done

2024-10-18 07:32 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +		nCompare = CompareLongint(solution1->GetHostClass()->GetDefinition()->GetMemoryMin(),
nb procs puis mémoire puis disque

2024-10-18 08:08 UTC, marcboulle approved these changes
LGTM
Deux petites améliorations de détail, si cela te convient

2024-10-18 08:08 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	if (nCompare == 0)
on peut remplacer le premier "if (nCompare == 0)" par un "else" avec un bloc englobant les trois dernières comparaison

2024-10-18 08:08 UTC, marcboulle commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	assert(nCompare != 0);
Cette assertion n'est pas intuitive a priori: commenter que c'est du au fait que deux solutions sont nécessairement distinctes par construction

2024-10-18 08:48 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	if (nCompare == 0)
done

2024-10-18 08:48 UTC, bruno-at-orange commented on src/Parallel/PLParallelTask/RMParallelResourceManager.cpp
> +	assert(nCompare != 0);
done

2024-10-18 08:52 UTC, merged