231 refactor coclustering iv by removing management of antecedent
KhiopsML/khiops pull request #447
Opened 2024-11-13 15:44 UTC by carinehue

Implémentation proto supprimant l'utilisation de l'antecedent
Correction de bug mémoire et d'un bug de calcul de cout
Nouvelle version de LearningTest suite a ces corrections

2024-11-14 15:20 UTC, marcboulle requested changes
Quelques suggestions de modification des noms et prototypes pour les nouvelles méthodes, à discuter, puis à prendre en compte éventuellement dans un nouveau point de commit.

Sinon, éventuellement supprimer les warnings suivants de KWDataGridOptimizer::PROTOGenerateNeighbourSolution
- `Learning\KWDataPreparation\KWDataGridOptimizer.cpp(2123): warning C4101: 'nMaxAttributeNumber' : variable locale non référencée`
- `Learning\KWDataPreparation\KWDataGridOptimizer.cpp(2122): warning C4101: 'nMandatoryAttributeNumber' : variable locale non référencée`

Et commencer à préparer la prochaine issue pour la suite des travaux sur la suppression des antécédents.
Par exemple: `Finalize removing management of "antecedent" in coclustering IV`
avec ce qui reste à faire, plus nettoyage des balises `// CH IV...`, `// CH ...`

2024-11-14 15:20 UTC, marcboulle commented on src/Learning/KWDataPreparation/KWDataGridManager.h
>  							 const KWDGInnerAttributes* referenceInnerAttributes,
Pourrais-on avoir le même pattern qu'avec les autres méthodes (ExportTerminalDataGrid, ExportNullDataGrid) qui utilisent implicitement le GetSourceDataGrid() du DataGridManager?

` void ExportDataGridWithRandomizedInnerAttributes(const KWDGInnerAttributes* referenceInnerAttributes,
							 KWDataGrid* targetDataGrid, int nTargetTokenNumber);`

2024-11-14 15:20 UTC, marcboulle commented on src/Learning/KWDataPreparation/KWDataGridManager.h
> +	void ExportDataGridWithMergedInnerAttributes(const KWDataGrid* inputDataGrid,
Pourrait-on avoir le même pattern qu'avec les autres méthodes (ExportTerminalDataGrid, ExportNullDataGrid) qui utilisent implicitement le GetSourceDataGrid() du DataGridManager?

`void  ExportDataGridWithMergedInnerAttributes(const KWDGInnerAttributes* mergedInnerAttributes,
						     KWDataGrid* targetDataGrid);`

2024-11-14 15:20 UTC, marcboulle commented on src/Learning/KWDataPreparation/KWDataGridManager.h
> +							 KWDataGrid* targetDataGrid);
Pourrait-on avoir le même pattern qu'avec les autres méthodes (ExportTerminalDataGrid, ExportNullDataGrid) qui utilisent implicitement le GetSourceDataGrid() du DataGridManager?
Plus renommer la méthode, et avoir un paramètre de type KWDGInnerAttributes, comme les méthodes similaires?

`void ExportReferenceDataGridWithGivenInnerAttributes(const KWDataGrid* inputDataGrid,
							     const KWDataGrid* tokenizedDataGrid,
							     KWDataGrid* targetDataGrid);`
->
`void ExportDataGridWithReferenceInnerAttributes(const KWDGInnerAttributes* referenceInnerAttributes,
							     KWDataGrid* targetDataGrid);`
- le inputDataGrid du DataGridManager doit être l'ancien tokenizedDataGrid
- le referenceInnerAttributes provient de l'ancien inputDataGrid->GetInnerAttributes()

2024-11-14 15:20 UTC, marcboulle commented on src/Learning/KWDataPreparation/KWDataGridMerger.cpp
> +				     << dDataGridTotalCost + dBestDeltaCost << "\t" << *bestPartMerge << flush << endl;
flush inutile, puisqu'il y a endl ensuite
`<< flush << endl`-> `<< endl`

2024-11-14 15:20 UTC, marcboulle commented on src/Learning/KWDataPreparation/KWDataGridMerger.cpp
>  int KWDGMPartMergeCompare(const void* elem1, const void* elem2)
Il faut reprendre la variante provenant de la branche dev (il y a du y avoire un problème dans le rebase).

Variante à utiliser:
```
int KWDGMPartMergeCompare(const void* elem1, const void* elem2)
{
	int nCompare;
	KWDGMPartMerge* partMerge1;
	KWDGMPartMerge* partMerge2;
	double dDiff;
	ALString sFirstPartLabel1;
	ALString sSecondPartLabel1;
	ALString sFirstPartLabel2;
	ALString sSecondPartLabel2;
	ALString sSwapPartLabel;

	require(elem1 != NULL);
	require(elem2 != NULL);

	// Acces aux fusions
	partMerge1 = cast(KWDGMPartMerge*, *(Object**)elem1);
	partMerge2 = cast(KWDGMPartMerge*, *(Object**)elem2);
	assert(partMerge1->Check());
	assert(partMerge2->Check());

	// Calcul de la difference, avec tolerance pour favoriser la stabilite
	nCompare = 0;
	dDiff = partMerge1->GetTruncatedMergeCost() - partMerge2->GetTruncatedMergeCost();
	if (dDiff > 0)
		nCompare = 1;
	else if (dDiff < 0)
		nCompare = -1;

	// Si egalite, on compare sur les nom de des attributs, puis sur celui des parties
	// On ne peut se baser sur le nombre de cellules des fusions, qui varie a cout egal,
	// ce qui empeche les optimisation poussees visant a ne reevaluer que les fusions impactees
	if (nCompare == 0)
	{
		// On se base d'abord sur le libelle de l'attribut
		// (on pourrait avoir des attribut differents ayant meme libelle de partie)
		assert(partMerge1->GetPart1()->GetAttribute() == partMerge1->GetPart2()->GetAttribute());
		assert(partMerge2->GetPart1()->GetAttribute() == partMerge2->GetPart2()->GetAttribute());
		nCompare = partMerge1->GetPart1()->GetAttribute()->GetAttributeName().Compare(
		    partMerge2->GetPart1()->GetAttribute()->GetAttributeName());

		// On se base ensuite sur le libelle du plus petit des deux libelles de partie
		if (nCompare == 0)
		{
			// Collecte des libelles de parties pour le Merge 1
			sFirstPartLabel1 = partMerge1->GetPart1()->GetObjectLabel();
			sSecondPartLabel1 = partMerge1->GetPart2()->GetObjectLabel();
			if (sFirstPartLabel1 > sSecondPartLabel1)
			{
				sSwapPartLabel = sSecondPartLabel1;
				sSecondPartLabel1 = sFirstPartLabel1;
				sFirstPartLabel1 = sSwapPartLabel;
			}

			// Collecte des libelles de parties pour le Merge 2
			sFirstPartLabel2 = partMerge2->GetPart1()->GetObjectLabel();
			sSecondPartLabel2 = partMerge2->GetPart2()->GetObjectLabel();
			if (sFirstPartLabel2 > sSecondPartLabel2)
			{
				sSwapPartLabel = sSecondPartLabel2;
				sSecondPartLabel2 = sFirstPartLabel2;
				sFirstPartLabel2 = sSwapPartLabel;
			}

			// Comparaison des libelles
			nCompare = sFirstPartLabel1.Compare(sFirstPartLabel2);
			if (nCompare == 0)
				nCompare = sSecondPartLabel1.Compare(sSecondPartLabel2);
		}
	}
	return nCompare;
}
```

2024-11-15 13:55 UTC, carinehue commented on src/Learning/KWDataPreparation/KWDataGridMerger.cpp
>  int KWDGMPartMergeCompare(const void* elem1, const void* elem2)
pris en compte

2024-11-15 13:55 UTC, carinehue commented on src/Learning/KWDataPreparation/KWDataGridMerger.cpp
> +				     << dDataGridTotalCost + dBestDeltaCost << "\t" << *bestPartMerge << flush << endl;
pris en compte

2024-11-15 13:56 UTC, carinehue commented on src/Learning/KWDataPreparation/KWDataGridManager.h
> +							 KWDataGrid* targetDataGrid);
reporté à l'issue https://github.com/KhiopsML/khiops/issues/454

2024-11-15 13:56 UTC, carinehue commented on src/Learning/KWDataPreparation/KWDataGridManager.h
> +	void ExportDataGridWithMergedInnerAttributes(const KWDataGrid* inputDataGrid,
reporté à l'issue https://github.com/KhiopsML/khiops/issues/454

2024-11-20 15:41 UTC, marcboulle approved these changes
LGTM

2024-11-22 12:59 UTC, merged