Add learningtest lite to the repo
KhiopsML/khiops pull request #46
Opened 2023-07-10 14:02 UTC by bruno-at-orange

- Add LearningTest for testing khiops packages (deb, rpm and .exe)
  - Iris dataset
  - Standard/Iris scenarios and references for Khiops and Khiops coclustering
  - python library to compare results and references
- Improve workflows to build rpm and deb
- Add action to run Iris test and check results
- fix several issues in rpm and deb packages

2023-07-10 14:52 UTC, felipe-olmos-orange requested changes
Why not making executing the test action after the unit-test as well ? (and rename `run-unit-test` to just `run-tests`

2023-07-10 14:52 UTC, felipe-olmos-orange commented on .github/workflows/pack-debian.yml
> +  test:
I would name it `test-package-deb`

2023-07-10 14:52 UTC, felipe-olmos-orange commented on .github/workflows/pack-rpm.yml
> +          cmake --build build --parallel --target MODL${{ env.MPI_SUFFIX }} MODL_Coclustering${{ env.MPI_SUFFIX }} KhiopsNativeInterface
add some "\" to make shorter lines

2023-07-10 14:52 UTC, felipe-olmos-orange commented on .gitignore
> +comparisonResults.log
-  put the learning test exceptions as I tried to above (the path would be `test/LearningTest/*/*/*/results`, etc). We could have another "results" directory that we don't want to ignore.
- `__pycache__` should be on its own section (python)

2023-07-10 14:52 UTC, folmos-at-orange commented on packaging/linux/common/khiops-env
> +#!/bin/bash
Isn't this file generated ?

2023-07-10 14:52 UTC, felipe-olmos-orange commented on test/LearningTest/TestKhiops/Standard/Iris/results.ref/Modeling.kdic
> +#Khiops 10.1
Why not adding all Standard ?

2023-07-10 15:25 UTC, bruno-at-orange commented on test/LearningTest/TestKhiops/Standard/Iris/results.ref/Modeling.kdic
> +#Khiops 10.1
because I don't need all standard to test the packaging

2023-07-10 15:25 UTC, bruno-at-orange commented on packaging/linux/common/khiops-env
> +#!/bin/bash
no

2023-07-10 15:32 UTC, felipe-olmos-orange commented on test/LearningTest/TestKhiops/Standard/Iris/results.ref/Modeling.kdic
> +#Khiops 10.1
Ok. Maybe later we'll add Standard.

2023-07-10 15:35 UTC, bruno-at-orange commented
> Why not making executing the test action after the unit-test as well ? (and rename `run-unit-test` to just `run-tests`

because the action tests the khiops package: it runs `khiops` and not `MODL`. Its purpose is to test the `khiops-env`+ `khiops`scripts and the good execution of Khiops on every distro

2023-07-11 07:49 UTC, felipe-olmos-orange commented
> > Why not making executing the test action after the unit-test as well ? (and rename `run-unit-test` to just `run-tests`
> 
> because the action tests the khiops package: it runs `khiops` and not `MODL`. Its purpose is to test the `khiops-env`+ `khiops`scripts and the good execution of Khiops on every distro

Ok

2023-07-11 07:51 UTC, felipe-olmos-orange requested changes

2023-07-11 07:51 UTC, felipe-olmos-orange commented on .gitignore
> +comparisonResults.log
Hello, just this change and it will LGTM

2023-07-11 11:57 UTC, felipe-olmos-orange approved these changes

2023-07-11 12:17 UTC, merged