Stop saving coclustering reports under deprecated format .khc
KhiopsML/khiops pull request #475
Opened 2024-11-27 16:31 UTC by carinehue

Evolution du code :
- Suppression de toutes les methodes et portions de code associees au format KHC. Exception : la reconnaissance du format khc est maintenue dans la methode CCCoclusteringReport::DetectFileFormatAndEncoding afin de pouvoir delivrer un message
 a l'utilisateur qui utiliserait cet ancien format
- Renommage des methodes Read/WriteJSON en Read/Write car JSON devient l'unique format
- Micro-correction de caracteres accentues dans CCCoclusteringReport.cpp

Jeux de test CICD :
- Nettoyage des resultats de test CICD dans TestCoclustering :
	- en enlevant des results.ref les coclusterings au format KHC
	- en modifiant les test.prm qui prenaient en entree des coclusterings au format KHC pour qu'ils utilisent des fichiers JSON
- Nettoyage des repertoires de jeux de test SimplifyAdultV75 : suppression car ancien format KHC avant Numerical et Categorical DeployDistributionAnnotatedMushroom/JSONDeployDistributionAnnotatedMushroom : on conserve uniquement DeployDistributionAnnotatedMushroom avec format JSON JSONSimplifyIris -> SimplifyIris :
JSONSimplifyAdultMissing -> SimplifyAdultMissing
- Ajout d'un test pour le cas d'utilisation de l'ancien format KHC : SimplifyIrisDeprecatedKHCFormat

2024-11-28 09:52 UTC, marcboulle requested changes
Quelques remarques et suggestion

Pourras tu m'envoyer tout le contenu de LearningTest\TestCoclustering\Standard?

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCAnalysisResults.dd
> +3;InputCoclusteringFileName        ;ALString;           ;true;Input coclustering report
Est-ce que le .dd a été régénéré par le générateur de vue?
Cf. https://github.com/KhiopsML/khiops/wiki/Building-Khiops , option `GENERATE_VIEWS` à `ON`

Cela permettrait de vérifier que tous les fichier CCAnalysisResults*.* sont valides vis-à-vis du processus de régénération des vues.

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.cpp
> +	if (nFileFormat == JSON)
Suggestion:
- supprimer les deux méthodes ReadGenericReport et ReadGenericReportHeader
- déplacer leur implémentation vers ReadReport et ReadReportHeader
- sortir rapidement dès le format est incorrect
```
bOk = nFileFormat == JSON;

// On arrete l'analyse si le format est incorrect
if (not bOk)
  return;
```
- continuer les instruction de facon standard ensuite (sans condition de type `if (nFileFormat == JSON)`)

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.cpp
> +	bOk = nFileFormat == JSON;
Cf. remarque suppression méthode ReadGenerticReport

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +		//if (bWriteOk and GetAnalysisResults()->GetExportAsKhc())
Supprimer ces instruction commentées

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +		//if (bOk and GetAnalysisResults()->GetExportAsKhc())
Supprimer ces instructions commentées

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +	/*if (bOk and (nTaskId == TaskBuildCoclustering or nTaskId == TaskPostProcessCoclustering) and
Supprimer ces instruction commentées

2024-11-28 09:52 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCLearningProblemToolView.cpp
> +	    "Select input coclustering", "Open", "FileChooser", "Coclustering\nkhcj\njson", "InputCoclusteringFileName",
On peut ne garder que le format .khcj (exclure le .json)

2024-11-28 13:14 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCLearningProblemToolView.cpp
> +	    "Select input coclustering", "Open", "FileChooser", "Coclustering\nkhcj\njson", "InputCoclusteringFileName",
fait

2024-11-28 13:16 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +	/*if (bOk and (nTaskId == TaskBuildCoclustering or nTaskId == TaskPostProcessCoclustering) and
ok

2024-11-28 13:16 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +		//if (bOk and GetAnalysisResults()->GetExportAsKhc())
ok

2024-11-28 13:16 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCLearningProblem.cpp
> +		//if (bWriteOk and GetAnalysisResults()->GetExportAsKhc())
ok

2024-11-28 16:42 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCLearningProblemToolView.cpp
> +	    "Select input coclustering", "Open", "FileChooser", "Coclustering\nkhcj\njson", "InputCoclusteringFileName",
ok

2024-11-28 16:43 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.cpp
> +	if (nFileFormat == JSON)
ok

2024-11-28 16:43 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.cpp
> +	bOk = nFileFormat == JSON;
ok

2024-11-28 16:43 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCAnalysisResults.dd
> +3;InputCoclusteringFileName        ;ALString;           ;true;Input coclustering report
ok

2024-11-29 10:11 UTC, marcboulle requested changes
Après vérification de la modification de tous les jeux de test de LearningTest\TestCoclustering, il reste quelques problèmes résiduels à régler.

Standard
- AllCCResultsApiMode: contenu de SubDir, avec un .khc
- AllCCResultsStandardMode: contenu de SubDir, avec un .khc
- DeployDistributionAnnotatedMushroom: un .bak en trop

SmallInstability: problème principal
- NumericalRounding: perte de précision numérique dans le SimplifiedCoclustering.khcj

Bugs
- BugSimplifySpliceJunction: Coclustering.khc à supprimer
- MixedAsciiUTF8Chars: supprimer le suffixe inutile _KHC

2024-11-29 10:11 UTC, marcboulle commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.h
> +	// Suffix des fichiers de rapports au format json: khcj depuis les rapports au format Khiops V10
Typo: Suffixe

2024-11-29 14:48 UTC, carinehue commented on src/Learning/MODL_Coclustering/CCCoclusteringReport.h
> +	// Suffix des fichiers de rapports au format json: khcj depuis les rapports au format Khiops V10
Pris en compte sauf problème de perte de précision numérique qui est affecté à l'issue 270 https://github.com/KhiopsML/khiops/pull/419

2024-11-29 15:18 UTC, marcboulle approved these changes
LGTM

Tous les LearningTest\TestCoclustering sont passés sur ma machine

2024-11-29 15:24 UTC, merged