Set default CMake generators per platform
KhiopsML/khiops pull request #67
Opened 2023-08-07 15:02 UTC by felipe-olmos-orange

We settle for `Ninja` in Windows and `Unix Makefiles` in Linux and MacOs.

2023-08-07 15:19 UTC, bruno-at-orange requested changes
On mac and Linux, I think it is better to let the default generator.
Why do we have to use makefile rather than Ninja ?

2023-08-07 15:51 UTC, felipe-olmos-orange commented
> On mac and Linux, I think it is better to let the default generator.
> Why do we have to use makefile rather than Ninja ?

The default generator in Linux and Mac are Makefiles. I think it is better to control explicitly the generator to have better reproducibility. The "default" generator may depend on the user's machine as CMake does many things automatically.

2023-08-08 07:38 UTC, bruno-at-orange commented
I don't like the idea to force developers to use a particular generator on their own environment. On production it is different, but we can specify the generator outside the preset (with the `-G` flag).
If you stuck on the idea to set it on the preset,  why did you choose Makefile ? Ninja is known to be faster and it builds natively in parallel (this is not the case for Makefile, whe have to add `--parallel`)...

2023-08-08 09:21 UTC, felipe-olmos-orange commented
After discussion we'll set the default generator for all platforms as `Ninja`

2023-08-09 20:05 UTC, felipe-olmos-orange commented
In addition to setting ninja-build as default for all presets:
- I installed ninja in all packaging containers
- I use presets in the linux build (for reproducibility)
  - So I installed a more recent version of cmake in the containers (from kitware's site)
- I renamed the containers to `khiopsml/khiops/khiopsdev` because the previous naming left them in the organizations repository and I couldn't overwrite them. I chose `khiopsdev` because people may confuse it with a docker **with** khiops inside. Additionally I set their visibility to "Internal".

2023-08-10 07:08 UTC, bruno-at-orange approved these changes
LGTM 
perhaps a minor change in .github/actions/build-khiops/action.yml

2023-08-10 07:08 UTC, bruno-at-orange commented on .github/actions/build-khiops/action.yml
> +    - name: Setup Ninja
I think you should add `if: ${{ runner.os != 'Linux' }}` because ninja is already on the docker images for Linux

2023-08-10 07:47 UTC, folmos-at-orange commented on .github/actions/build-khiops/action.yml
> +    - name: Setup Ninja
Yes, but when we run the tests we do in on Github's VM, and there is no Ninja

2023-08-10 07:49 UTC, bruno-at-orange commented on .github/actions/build-khiops/action.yml
> +    - name: Setup Ninja
OK...

2023-08-10 09:35 UTC, merged