Fix MODL_Coclustering double size in windows
KhiopsML/khiops pull request #97
Opened 2023-11-02 13:37 UTC by folmos-at-orange

The MODL_Coclustering.exe executable in windows had doubled in size because the MSVC link option `/INCREMENTAL` was activated.

This wasn't the case for the original build with VS projects.

2023-11-06 09:13 UTC, marcboulle reviewed
J'ai vérifié sur ma branche: ça corrige bien le problème ;)

Question
- pourquoi continuer à se référer à MPI_SUFFIX si on ne compile pas cet exe avec MPI (cf. genum)?

Suggestion
- si tu change les commentaires, il faudrait homogénéiser avec ceux des autres CMakeLists.txt (en particulier celui de MODL)

2023-11-08 08:36 UTC, folmos-at-orange commented
> J'ai vérifié sur ma branche: ça corrige bien le problème ;)
> 
> Question
> 
> * pourquoi continuer à se référer à MPI_SUFFIX si on ne compile pas cet exe avec MPI (cf. genum)?
Good question. This impacts the installation let's wait for @bruno-at-orange  to weigh in.

> Suggestion
> 
> * si tu change les commentaires, il faudrait homogénéiser avec ceux des autres CMakeLists.txt (en particulier celui de MODL)
**Ok**

2023-11-14 08:42 UTC, bruno-at-orange requested changes, later dismissed
Stop focusing on targets !

2023-11-14 08:42 UTC, bruno-at-orange commented on src/Learning/MODL_Coclustering/CMakeLists.txt
Je ne suis pas d'accord avec la modification des commentaires. Il faut que tu arretes de te focaliser sur les target. TOUT est target dans cmake. Par exemple pour, add_binary(TOTO) et add_executable(TITI) dans le commentaire, on ne va pas mettre qu'on ajoute la target TOTO et la target TOTI mais bien l'executable TOTO et la bibliothèque TITI car c'est ce qu'oin souhaite faire. Et que cmake passe par des targets, c'est secondaire et ça n'apporte absolument rien à  la comprehension du fichier CMakeList qu'on est en train de commenter. 
Ici en l'occurence on parle du binaire MODL_Coclustering ou du nom de ce binaire. D'ailleurs pour fedora on n'a pas du tout besoin de renommer la target mais bien le nom du binaire !!!
Mon commentaire n'était peut-être pas précis car je faisis un abus de le langage, en effet il ne faut pas renommer le binaire mais le nom du binaire, soit ! On aurait donc `on fedora, binaries names built with mpi must be suffixed by _mpich`. Je pense qu'il est important de commencer le commentairte par `on fedora` car ça ne concerne que fedora...

2023-11-14 10:03 UTC, folmos-at-orange commented on src/Learning/MODL_Coclustering/CMakeLists.txt
Ok. I will be more precise for each target type (binary or library). I would keep separated the code for each of them to avoid bugs.

2023-11-14 11:09 UTC, marcboulle approved these changes
Ok si seulement correction du bug de l'issue

2023-11-24 17:56 UTC, folmos-at-orange commented on src/Learning/MODL_Coclustering/CMakeLists.txt
It was also a formatting error of `cmake-format` I didn't mean to put `On Fedora` after the title of the section.

2023-11-27 12:40 UTC, marcboulle approved these changes
LGTM

2023-11-27 12:43 UTC, merged